baseURL = "https://roussev.dev"
languageCode = "en-us"
title = "Bogomil Roussev"
theme = "terminal"

[pagination]
  pagerSize = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of articles will be on this page
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  # default is orange
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # default is false
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

# Social media links
[[params.social]]
  name = "email"
  url = "mailto:bogomil.roussev@gmail.com"

[[params.social]]
  name = "github"
  url = "https://github.com/bogsi"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/bogomilroussev"

# Menu items
[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 1
  
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 2
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 4

# Syntax highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "monokai"

# Privacy settings
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Bogomil Roussev"
    subtitle = "AWS & Terraform Automation Consultant"
    owner = "Bogomil Roussev"
    keywords = "AWS, Terraform, Cloud, Infrastructure, Automation, DevOps"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Bogomil Roussev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "services"
        name = "Services"
        url = "/services"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 4

[build]
  writeStats = true

[server]
  enableCompression = true

[imaging]
  quality = 85
  resampleFilter = "lanczos"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true
