baseURL = "https://roussev.dev"
languageCode = "en-us"
title = "Bogomil Roussev"
theme = "terminal"

# Terminal theme settings
[params]
  # Terminal theme colors and styling
  themeColor = "orange"
  fullWidthTheme = false
  centerTheme = true
  
  # Site information
  author = "Bogomil Roussev"
  info = "AWS & Terraform Automation Consultant"
  description = "Cloud Infrastructure and Automation Solutions"
  keywords = "AWS, Terraform, Cloud, Infrastructure, Automation, DevOps"
  
  # Menu configuration
  showMenuItems = 4
  
  # Comments configuration
  [params.comments]
    # Disable comments by default
    enabled = false
    engine = "none"
    disqusShortname = ""

# Social media links
[[params.social]]
  name = "github"
  url = "https://github.com/bogsi"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/bogomilroussev"

# Menu items
[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 1
  
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 2
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 4

# Syntax highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "monokai"

# Privacy settings
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Bogomil Roussev"
    subtitle = "AWS & Terraform Automation Consultant"
    owner = "Bogomil Roussev"
    keywords = "AWS, Terraform, DevOps, Automation, Cloud Infrastructure"
    copyright = "© 2025 Bogomil Roussev"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Bogomil Roussev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "services"
        name = "Services"
        url = "/services/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "https://medium.com/@bogomilroussev"
        weight = 4

[build]
  writeStats = true

[server]
  enableCompression = true

[imaging]
  quality = 85
  resampleFilter = "lanczos"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true
