baseURL = 'https://roussev.dev'
languageCode = 'en-us'
title = 'Bogomil Roussev | AWS & Terraform Automation Consultant'
theme = 'terminal'

[params]
  # dir name of your main content (default is `content/posts`).
  contentTypeName = "posts"
  
  # Set theme colors
  themeColor = "green"
  
  # show selector to switch language
  showLanguageSelector = false
  
  # set theme to full screen width
  fullWidthTheme = true
  
  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  autoCover = true

  # Show reading time
  readingTime = true

  # Show table of contents
  Toc = true
  
  # Author info
  author = 'Bogomil Roussev'
  email = 'bogomil.roussev@gmail.com'
  phone = '+359 878 880 112'
  linkedin = 'https://www.linkedin.com/in/bogomilroussev/'
  github = 'https://github.com/bogsi'

  # Theme colors
  [params.style]
    backgroundColor = "#000000"
    foregroundColor = "#00ff00"
    accentColor = "#00ff00"
    borderColor = "#00ff00"

[languages]
  [languages.en]
    languageName = "English"
    title = "Bogomil Roussev"
    subtitle = "AWS & Terraform Automation Consultant"
    owner = "Bogomil Roussev"
    keywords = "AWS, Terraform, DevOps, Automation, Cloud Infrastructure"
    copyright = "© 2025 Bogomil Roussev"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Bogomil Roussev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "services"
        name = "Services"
        url = "/services/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "https://medium.com/@bogomilroussev"
        weight = 4

[markup]
  [markup.highlight]
    noClasses = false
